# Generated by Django 3.2.14 on 2022-08-21 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('qid', models.AutoField(primary_key=True, serialize=False)),
                ('query', models.CharField(max_length=250)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('search_engine', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('link', models.CharField(max_length=64)),
                ('qid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='metasearch.userquery')),
            ],
        ),
    ]
